#!/bin/bash

help(){
	printf "Usage:\n"
	printf "\t atom\t\t: Install GitHub Atom editor.\n"
	printf "\t brew\t\t: Install Homebrew.\n"
	printf "\t docker\t\t: Install Docker and associated toolchain.\n"
	printf "\t virtualbox\t: Install Homebrew.\n"
	printf "\t help\t\t: Show this help.\n"
}

install_atom(){
	brew cask install atom
}

install_brew(){
	command -v brew
	if [ "$?" -eq 1 ]; then
		printf "Installing brew...\n"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
}

install_docker(){
	# See https://stackoverflow.com/questions/40523307/brew-install-docker-does-not-include-docker-engine
	brew cask install docker
}

install_vagrant(){
	brew cask install vagrant
	brew cask install atom
}

CMD=$1
case "$CMD" in
	atom)
		install_atom
		;;
	brew)
		install_brew
		;;
	docker)
		install_docker
		;;
	virtualbox)
		./src/bin/virtualbox "${@:2}"
		;;
	* | -h | help)
		help
		;;
esac
