#!/bin/bash

# Simple script to allow BATS setup and run tests easily

help(){
	echo "Usage:"
	printf "\t setup\t\t: Sets up BATS framework if not done already.\n"
	printf "\t healthcheck\t: Run health check.\n"
	printf "\t tests\t\t: Run tests.\n"
	printf "\t help\t\t: Show this help.\n"
	exit 0
}

run_healthcheck(){
	./setup

	bats tests/bats/healthcheck_*
}

run_tests(){
	./setup

	bats tests/bats/test_*
}

if [[ -z $1 ]];then
	help
fi

case $1 in
	setup)
		./setup
		;;
	hc | healthcheck)
		run_healthcheck
		;;
	tests)
		run_tests
		;;
	* | help)
		help
		;;
esac
